class LocationModel {
  final String name;
  final String flag;

  const LocationModel({
    required this.name,
    required this.flag,
  });

  static const List<LocationModel> locations = [
    LocationModel(name: "Afghanistan", flag: "🇦🇫"),
    LocationModel(name: "Algeria", flag: "🇩🇿"),
    LocationModel(name: "Andorra", flag: "🇦🇩"),
    LocationModel(name: "Argentina", flag: "🇦🇷"),
    LocationModel(name: "Australia", flag: "🇦🇺"),
    LocationModel(name: "Austria", flag: "🇦🇹"),
    LocationModel(name: "Bahrain", flag: "🇧🇭"),
    LocationModel(name: "Belgium", flag: "🇧🇪"),
    LocationModel(name: "Comoros", flag: "🇰🇲"),
    LocationModel(name: "Djibouti", flag: "🇩🇯"),
    LocationModel(name: "Egypt", flag: "🇪🇬"),
    LocationModel(name: "France", flag: "🇫🇷"),
    LocationModel(name: "Germany", flag: "🇩🇪"),
    LocationModel(name: "Greece", flag: "🇬🇷"),
    LocationModel(name: "Iraq", flag: "🇮🇶"),
    LocationModel(name: "Italy", flag: "🇮🇹"),
    LocationModel(name: "Japan", flag: "🇯🇵"),
    LocationModel(name: "Jordan", flag: "🇯🇴"),
    LocationModel(name: "Kuwait", flag: "🇰🇼"),
    LocationModel(name: "Lebanon", flag: "🇱🇧"),
    LocationModel(name: "Libya", flag: "🇱🇾"),
    LocationModel(name: "Mauritania", flag: "🇲🇷"),
    LocationModel(name: "Morocco", flag: "🇲🇦"),
    LocationModel(name: "Netherlands", flag: "🇳🇱"),
    LocationModel(name: "Norway", flag: "🇳🇴"),
    LocationModel(name: "Oman", flag: "🇴🇲"),
    LocationModel(name: "Palestine", flag: "🇵🇸"),
    LocationModel(name: "Poland", flag: "🇵🇱"),
    LocationModel(name: "Portugal", flag: "🇵🇹"),
    LocationModel(name: "Qatar", flag: "🇶🇦"),
    LocationModel(name: "Russia", flag: "🇷🇺"),
    LocationModel(name: "Saudi Arabia", flag: "🇸🇦"),
    LocationModel(name: "Somalia", flag: "🇸🇴"),
    LocationModel(name: "Spain", flag: "🇪🇸"),
    LocationModel(name: "Sudan", flag: "🇸🇩"),
    LocationModel(name: "Sweden", flag: "🇸🇪"),
    LocationModel(name: "Switzerland", flag: "🇨🇭"),
    LocationModel(name: "Syria", flag: "🇸🇾"),
    LocationModel(name: "Tunisia", flag: "🇹🇳"),
    LocationModel(name: "Turkey", flag: "🇹🇷"),
    LocationModel(name: "United Arab Emirates", flag: "🇦🇪"),
    LocationModel(name: "United Kingdom", flag: "🇬🇧"),
    LocationModel(name: "United States", flag: "🇺🇸"),
    LocationModel(name: "Yemen", flag: "🇾🇪"),
  ];
}