// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOXurwMa7-3souFeMSecca4D4wLfSo0g',
    appId: '1:901378013831:web:03e0b32de35b1fc71fd622',
    messagingSenderId: '901378013831',
    projectId: 'a5barna-efa19',
    authDomain: 'a5barna-efa19.firebaseapp.com',
    storageBucket: 'a5barna-efa19.firebasestorage.app',
    measurementId: 'G-8QFDG2HP2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOws2DidjRpkJssraE82wIAZzGOoA3Q7k',
    appId: '1:901378013831:android:fca337460acf4a721fd622',
    messagingSenderId: '901378013831',
    projectId: 'a5barna-efa19',
    storageBucket: 'a5barna-efa19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1HkFEFO7ye2Ah3_T9kbT5aTZUyfWBIc',
    appId: '1:901378013831:ios:2adac64ebe3ebf371fd622',
    messagingSenderId: '901378013831',
    projectId: 'a5barna-efa19',
    storageBucket: 'a5barna-efa19.firebasestorage.app',
    iosBundleId: 'com.akhbarna.akhbarna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1HkFEFO7ye2Ah3_T9kbT5aTZUyfWBIc',
    appId: '1:901378013831:ios:2adac64ebe3ebf371fd622',
    messagingSenderId: '901378013831',
    projectId: 'a5barna-efa19',
    storageBucket: 'a5barna-efa19.firebasestorage.app',
    iosBundleId: 'com.akhbarna.akhbarna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOXurwMa7-3souFeMSecca4D4wLfSo0g',
    appId: '1:901378013831:web:bd7ea7e74f4cc6ae1fd622',
    messagingSenderId: '901378013831',
    projectId: 'a5barna-efa19',
    authDomain: 'a5barna-efa19.firebaseapp.com',
    storageBucket: 'a5barna-efa19.firebasestorage.app',
    measurementId: 'G-6Z5FB2LSTS',
  );

}
